---
- name: Install the Docker package
  hosts: tool-server
  become: true
  tasks:
    - name: Install the Docker package
      yum:
        name: docker
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Set a hostname
      hostname:
        name: tool-server