---
- hosts: all
  vars_files:
   - variables
  tasks:
  - name: Generating Log on VSD
    command: /opt/vsd/install/collectlog.sh -l /backup -d 1  

  - name: Getting Log file name
    shell: (ls /backup/) | grep {{ date }}
    register: command_output
  
  - name: Copying collected log on to your computer 
    fetch:
      src: /backup/{{ command_output.stdout }}
      dest: "{{ local_dest }}"
      flat: yes
  
  - name: Copying collected log to Nokia SFTP Server
    copy:
      src: /Users/[username goes here]/Documents/Ansible/mylog-*
      dest: /home/[username goes here]
      owner: [username goes here]
      group: [username goes here]
      mode: '0644'
    
      