---
 
- name: Copy file to remote server
  hosts: nfs_server
  become: true
  tasks:
    - name: Update server
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Download Node Exporter
  hosts: nfs_server
  tasks:
    - name: Downloading Node Exporter....
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /home/mohi/
        
- name: Unpack file on server
  hosts: nfs_server
  tasks:
    - name: unpacking file on server....
      unarchive:
        src: /home/mohi/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /home/mohi/
        remote_src: yes 

- name: Create Node Exporter User and Group
  become: true
  hosts: nfs_server
  tasks:
    - name: Creating Node Exporter Group...
      group: 
        name: node_exporter
        state: present 
    - name: Creating Node Exporter User...
      user:
        name: node_exporter
        state: present

- name: Copy Node Exporter to /usr/local/bin
  hosts: nfs_server
  become: true
  tasks:
    - name: Copying Node Exporter to /usr/local/bin
      copy:
        src: /home/mohi/node_exporter-1.3.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
        owner: node_exporter
        group: node_exporter
        mode: u=rwx 
        remote_src: true 

- name: Create Node Exporter Service
  hosts: nfs_server
  become: true
  tasks:
    - name: Creating Node Exporter Service 
      copy: 
        src: /Users/mohammed/Documents/Ansible/node_exporter.service
        dest: /etc/systemd/system/
        owner: node_exporter
        group: node_exporter
        mode: u=rwx

- name: Enable Node Exporter Service
  hosts: nfs_server
  become: true
  #become_user: node_exporter 
  tasks: 
    - name: Enabling Node Exporter Service
      service:
        name: node_exporter 
        state: started

- name: Reload system daemon
  hosts: nfs_server
  become: true
  #become_user: node_exporter 
  tasks: 
    - name: Reloading system daemon
      systemd:
       name: node_exporter
       state: started
       daemon_reload: yes

- name: Ensure Node Exporter is running
  hosts: nfs_server
  become: true
  become_user: node_exporter
  tasks:
    - name: Ensuring Node Exporter is running
      shell: ps aux | grep node_exporter
      register: app_status
    - debug: msg={{app_status.stdout_lines}}  
    
    
       



